on:
  workflow_dispatch:
name: Build Package

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME_UNDERSCORE: zola
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: apt update && apt upgrade -y && apt install -y g++-mingw-w64-x86-64 && rustup target add x86_64-pc-windows-gnu && rustup toolchain install stable-x86_64-pc-windows-gnu
      - name: Release Win Build
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Release Build
        run: cargo build --release
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}
          path: target/release/${{ env.PROJECT_NAME_UNDERSCORE }}
